"""Initial  

Revision ID: dce0f45aceb2
Revises: 
Create Date: 2026-04-04 08:24:42.790832

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dce0f45aceb2'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('otp_secret', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('login_session',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('project',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('registration_token_hash', sa.String(), nullable=True),
    sa.Column('declared_os', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('ONLINE', 'OFFLINE', 'STALE', name='agentstatus'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('agent_version', sa.String(), nullable=True),
    sa.Column('capabilities_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_project_id'), 'agent', ['project_id'], unique=False)
    op.create_table('environment',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_environment_project_id'), 'environment', ['project_id'], unique=False)
    op.create_table('project_member',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'MEMBER', name='projectmemberrole'), nullable=False),
    sa.Column('invite_status', sa.Enum('PENDING', 'ACCEPTED', name='invitestatus'), nullable=False),
    sa.Column('invited_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('project_id', 'user_id')
    )
    op.create_table('task_template',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('metric_policy_json', sa.JSON(), nullable=False),
    sa.Column('approved_command', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_template_project_id'), 'task_template', ['project_id'], unique=False)
    op.create_table('agent_bootstrap_token',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('agent_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agent.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_bootstrap_token_agent_id'), 'agent_bootstrap_token', ['agent_id'], unique=False)
    op.create_table('environment_member',
    sa.Column('environment_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('OPERATOR', 'OBSERVER', name='environmentmemberrole'), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['environment_id'], ['environment.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('environment_id', 'user_id')
    )
    op.create_table('host',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('environment_id', sa.String(length=36), nullable=False),
    sa.Column('agent_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('internal_identifier', sa.String(), nullable=False),
    sa.Column('descriptive_fields_json', sa.JSON(), nullable=False),
    sa.Column('os_name', sa.String(), nullable=True),
    sa.Column('hostname', sa.String(), nullable=True),
    sa.Column('primary_ipv4', sa.String(), nullable=True),
    sa.Column('primary_ipv6', sa.String(), nullable=True),
    sa.Column('metadata_last_refreshed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agent.id'], ),
    sa.ForeignKeyConstraint(['environment_id'], ['environment.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('environment_id', 'agent_id', name='uq_host_env_agent')
    )
    op.create_index(op.f('ix_host_agent_id'), 'host', ['agent_id'], unique=False)
    op.create_index(op.f('ix_host_environment_id'), 'host', ['environment_id'], unique=False)
    op.create_table('schedule_rule',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('environment_id', sa.String(length=36), nullable=False),
    sa.Column('task_template_id', sa.String(length=36), nullable=False),
    sa.Column('cron_expr', sa.String(), nullable=False),
    sa.Column('target_selector_json', sa.JSON(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('next_run_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['environment_id'], ['environment.id'], ),
    sa.ForeignKeyConstraint(['task_template_id'], ['task_template.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedule_rule_environment_id'), 'schedule_rule', ['environment_id'], unique=False)
    op.create_index(op.f('ix_schedule_rule_task_template_id'), 'schedule_rule', ['task_template_id'], unique=False)
    op.create_table('metric_snapshot',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('environment_id', sa.String(length=36), nullable=False),
    sa.Column('host_id', sa.String(length=36), nullable=False),
    sa.Column('metric_kind', sa.String(), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.Column('value_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['environment_id'], ['environment.id'], ),
    sa.ForeignKeyConstraint(['host_id'], ['host.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metric_snapshot_environment_id'), 'metric_snapshot', ['environment_id'], unique=False)
    op.create_index(op.f('ix_metric_snapshot_host_id'), 'metric_snapshot', ['host_id'], unique=False)
    op.create_table('task_run',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('environment_id', sa.String(length=36), nullable=False),
    sa.Column('host_id', sa.String(length=36), nullable=False),
    sa.Column('agent_id', sa.String(length=36), nullable=False),
    sa.Column('task_template_id', sa.String(length=36), nullable=False),
    sa.Column('schedule_rule_id', sa.String(length=36), nullable=True),
    sa.Column('payload_override_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'LEASED', 'RUNNING', 'SUCCEEDED', 'FAILED', 'CANCELLED', 'EXPIRED', name='taskrunstatus'), nullable=False),
    sa.Column('lease_token', sa.String(), nullable=True),
    sa.Column('leased_until', sa.DateTime(), nullable=True),
    sa.Column('attempt_no', sa.Integer(), nullable=False),
    sa.Column('queued_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agent.id'], ),
    sa.ForeignKeyConstraint(['environment_id'], ['environment.id'], ),
    sa.ForeignKeyConstraint(['host_id'], ['host.id'], ),
    sa.ForeignKeyConstraint(['schedule_rule_id'], ['schedule_rule.id'], ),
    sa.ForeignKeyConstraint(['task_template_id'], ['task_template.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_run_agent_id'), 'task_run', ['agent_id'], unique=False)
    op.create_index(op.f('ix_task_run_environment_id'), 'task_run', ['environment_id'], unique=False)
    op.create_index(op.f('ix_task_run_host_id'), 'task_run', ['host_id'], unique=False)
    op.create_index(op.f('ix_task_run_task_template_id'), 'task_run', ['task_template_id'], unique=False)
    op.create_table('task_run_result',
    sa.Column('task_run_id', sa.String(length=36), nullable=False),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('stdout_text', sa.Text(), nullable=True),
    sa.Column('stderr_text', sa.Text(), nullable=True),
    sa.Column('summary_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['task_run_id'], ['task_run.id'], ),
    sa.PrimaryKeyConstraint('task_run_id')
    )
    op.create_table('telemetry_record',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('task_run_id', sa.String(length=36), nullable=False),
    sa.Column('environment_id', sa.String(length=36), nullable=False),
    sa.Column('host_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('collected_at', sa.DateTime(), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('payload_hash', sa.String(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['environment_id'], ['environment.id'], ),
    sa.ForeignKeyConstraint(['host_id'], ['host.id'], ),
    sa.ForeignKeyConstraint(['task_run_id'], ['task_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telemetry_record_environment_id'), 'telemetry_record', ['environment_id'], unique=False)
    op.create_index(op.f('ix_telemetry_record_host_id'), 'telemetry_record', ['host_id'], unique=False)
    op.create_index(op.f('ix_telemetry_record_task_run_id'), 'telemetry_record', ['task_run_id'], unique=True)
    op.create_table('graph_edge',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('environment_id', sa.String(length=36), nullable=False),
    sa.Column('source_host_id', sa.String(length=36), nullable=False),
    sa.Column('target_host_id', sa.String(length=36), nullable=True),
    sa.Column('target_label', sa.String(), nullable=True),
    sa.Column('relation_kind', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('observed_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('telemetry_record_id', sa.String(length=36), nullable=True),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['environment_id'], ['environment.id'], ),
    sa.ForeignKeyConstraint(['source_host_id'], ['host.id'], ),
    sa.ForeignKeyConstraint(['target_host_id'], ['host.id'], ),
    sa.ForeignKeyConstraint(['telemetry_record_id'], ['telemetry_record.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_graph_edge_environment_id'), 'graph_edge', ['environment_id'], unique=False)
    op.create_index(op.f('ix_graph_edge_source_host_id'), 'graph_edge', ['source_host_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_graph_edge_source_host_id'), table_name='graph_edge')
    op.drop_index(op.f('ix_graph_edge_environment_id'), table_name='graph_edge')
    op.drop_table('graph_edge')
    op.drop_index(op.f('ix_telemetry_record_task_run_id'), table_name='telemetry_record')
    op.drop_index(op.f('ix_telemetry_record_host_id'), table_name='telemetry_record')
    op.drop_index(op.f('ix_telemetry_record_environment_id'), table_name='telemetry_record')
    op.drop_table('telemetry_record')
    op.drop_table('task_run_result')
    op.drop_index(op.f('ix_task_run_task_template_id'), table_name='task_run')
    op.drop_index(op.f('ix_task_run_host_id'), table_name='task_run')
    op.drop_index(op.f('ix_task_run_environment_id'), table_name='task_run')
    op.drop_index(op.f('ix_task_run_agent_id'), table_name='task_run')
    op.drop_table('task_run')
    op.drop_index(op.f('ix_metric_snapshot_host_id'), table_name='metric_snapshot')
    op.drop_index(op.f('ix_metric_snapshot_environment_id'), table_name='metric_snapshot')
    op.drop_table('metric_snapshot')
    op.drop_index(op.f('ix_schedule_rule_task_template_id'), table_name='schedule_rule')
    op.drop_index(op.f('ix_schedule_rule_environment_id'), table_name='schedule_rule')
    op.drop_table('schedule_rule')
    op.drop_index(op.f('ix_host_environment_id'), table_name='host')
    op.drop_index(op.f('ix_host_agent_id'), table_name='host')
    op.drop_table('host')
    op.drop_table('environment_member')
    op.drop_index(op.f('ix_agent_bootstrap_token_agent_id'), table_name='agent_bootstrap_token')
    op.drop_table('agent_bootstrap_token')
    op.drop_index(op.f('ix_task_template_project_id'), table_name='task_template')
    op.drop_table('task_template')
    op.drop_table('project_member')
    op.drop_index(op.f('ix_environment_project_id'), table_name='environment')
    op.drop_table('environment')
    op.drop_index(op.f('ix_agent_project_id'), table_name='agent')
    op.drop_table('agent')
    op.drop_table('project')
    op.drop_table('login_session')
    op.drop_table('user')
    # ### end Alembic commands ###
