"""upd  

Revision ID: 140f8250dfe5
Revises: 441783341046
Create Date: 2025-10-25 22:17:32.442546

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '140f8250dfe5'
down_revision: str | Sequence[str] | None = '441783341046'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('check_task', sa.Column('failed_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('check_task', 'failed_count')
    # ### end Alembic commands ###
