"""upd  

Revision ID: 441783341046
Revises: d9af453b86a5
Create Date: 2025-10-25 21:36:18.570908

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '441783341046'
down_revision: str | Sequence[str] | None = 'd9af453b86a5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('check', sa.Column('acked_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('check', 'acked_at')
    # ### end Alembic commands ###
